# Лабораторная работа №2

In [55]:
import pandas as pd
from datetime import datetime

In [56]:
dataframe = pd.read_csv("../lab2/data/BikeData.csv")
dataframe

,Date,Hour,Temperature,Humidity,Wind speed,Rainfall,Snowfall,Seasons,Holiday,Functioning Day,Partner 1,Partner 2
0,01/12/2017,0,-5.2,37,2.2,0.0,0.0,Winter,No Holiday,Yes,207,50
1,01/12/2017,1,-5.5,38,0.8,0.0,0.0,Winter,No Holiday,Yes,139,80
2,01/12/2017,2,-6.0,39,1.0,0.0,0.0,Winter,No Holiday,Yes,22,140
3,01/12/2017,3,-6.2,40,0.9,0.0,0.0,Winter,No Holiday,Yes,43,105
4,01/12/2017,4,-6.0,36,2.3,0.0,0.0,Winter,No Holiday,Yes,59,38
...,...,...,...,...,...,...,...,...,...,...,...,...
8755,30/11/2018,19,4.2,34,2.6,0.0,0.0,Autumn,No Holiday,Yes,467,177
8756,30/11/2018,20,3.4,37,2.3,0.0,0.0,Autumn,No Holiday,Yes,296,63
8757,30/11/2018,21,2.6,39,0.3,0.0,0.0,Autumn,No Holiday,Yes,571,665
8758,30/11/2018,22,2.1,41,1.0,0.0,0.0,Autumn,No Holiday,Yes,171,457
8759,30/11/2018,23,1.9,43,1.3,0.0,0.0,Autumn,No Holiday,Yes,442,401

1) Создайте новую переменную Total_count, в которую записать общее количество арендованных велосипедов за каждый час.

In [57]:
dataframe['Total_count'] = dataframe['Partner 1'] + dataframe['Partner 2']
dataframe

,Date,Hour,Temperature,Humidity,Wind speed,Rainfall,Snowfall,Seasons,Holiday,Functioning Day,Partner 1,Partner 2,Total_count
0,01/12/2017,0,-5.2,37,2.2,0.0,0.0,Winter,No Holiday,Yes,207,50,257
1,01/12/2017,1,-5.5,38,0.8,0.0,0.0,Winter,No Holiday,Yes,139,80,219
2,01/12/2017,2,-6.0,39,1.0,0.0,0.0,Winter,No Holiday,Yes,22,140,162
3,01/12/2017,3,-6.2,40,0.9,0.0,0.0,Winter,No Holiday,Yes,43,105,148
4,01/12/2017,4,-6.0,36,2.3,0.0,0.0,Winter,No Holiday,Yes,59,38,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,30/11/2018,19,4.2,34,2.6,0.0,0.0,Autumn,No Holiday,Yes,467,177,644
8756,30/11/2018,20,3.4,37,2.3,0.0,0.0,Autumn,No Holiday,Yes,296,63,359
8757,30/11/2018,21,2.6,39,0.3,0.0,0.0,Autumn,No Holiday,Yes,571,665,1236
8758,30/11/2018,22,2.1,41,1.0,0.0,0.0,Autumn,No Holiday,Yes,171,457,628
8759,30/11/2018,23,1.9,43,1.3,0.0,0.0,Autumn,No Holiday,Yes,442,401,843

2) Удалите ряды Partner 1 и Partner 2

In [58]:
dataframe = dataframe.drop(columns=['Partner 1', 'Partner 2'])
dataframe

,Date,Hour,Temperature,Humidity,Wind speed,Rainfall,Snowfall,Seasons,Holiday,Functioning Day,Total_count
0,01/12/2017,0,-5.2,37,2.2,0.0,0.0,Winter,No Holiday,Yes,257
1,01/12/2017,1,-5.5,38,0.8,0.0,0.0,Winter,No Holiday,Yes,219
2,01/12/2017,2,-6.0,39,1.0,0.0,0.0,Winter,No Holiday,Yes,162
3,01/12/2017,3,-6.2,40,0.9,0.0,0.0,Winter,No Holiday,Yes,148
4,01/12/2017,4,-6.0,36,2.3,0.0,0.0,Winter,No Holiday,Yes,97
...,...,...,...,...,...,...,...,...,...,...,...
8755,30/11/2018,19,4.2,34,2.6,0.0,0.0,Autumn,No Holiday,Yes,644
8756,30/11/2018,20,3.4,37,2.3,0.0,0.0,Autumn,No Holiday,Yes,359
8757,30/11/2018,21,2.6,39,0.3,0.0,0.0,Autumn,No Holiday,Yes,1236
8758,30/11/2018,22,2.1,41,1.0,0.0,0.0,Autumn,No Holiday,Yes,628
8759,30/11/2018,23,1.9,43,1.3,0.0,0.0,Autumn,No Holiday,Yes,843

3) Преобразуйте переменную Date к стандартной форме (to_datetime).

In [59]:
# dataframe['Date'] = dataframe['Date'].dt.strftime('%d.%m.%Y')
dataframe['Date'] = pd.to_datetime(dataframe['Date'], format='%d/%m/%Y')
dataframe

,Date,Hour,Temperature,Humidity,Wind speed,Rainfall,Snowfall,Seasons,Holiday,Functioning Day,Total_count
0,2017-12-01,0,-5.2,37,2.2,0.0,0.0,Winter,No Holiday,Yes,257
1,2017-12-01,1,-5.5,38,0.8,0.0,0.0,Winter,No Holiday,Yes,219
2,2017-12-01,2,-6.0,39,1.0,0.0,0.0,Winter,No Holiday,Yes,162
3,2017-12-01,3,-6.2,40,0.9,0.0,0.0,Winter,No Holiday,Yes,148
4,2017-12-01,4,-6.0,36,2.3,0.0,0.0,Winter,No Holiday,Yes,97
...,...,...,...,...,...,...,...,...,...,...,...
8755,2018-11-30,19,4.2,34,2.6,0.0,0.0,Autumn,No Holiday,Yes,644
8756,2018-11-30,20,3.4,37,2.3,0.0,0.0,Autumn,No Holiday,Yes,359
8757,2018-11-30,21,2.6,39,0.3,0.0,0.0,Autumn,No Holiday,Yes,1236
8758,2018-11-30,22,2.1,41,1.0,0.0,0.0,Autumn,No Holiday,Yes,628
8759,2018-11-30,23,1.9,43,1.3,0.0,0.0,Autumn,No Holiday,Yes,843

4) Определите сколько велосипедов было выдано в день, месяц и число которого совпадает с днем выполнения этого задания. Определите, какой это был день недели.

In [60]:
current_date = datetime.now().date()
current_month = current_date.month
current_day = current_date.day

current_date_dataframe = dataframe[(dataframe['Date'].dt.month == current_month) & (dataframe['Date'].dt.day == current_day)]
current_date_count = current_date_dataframe['Total_count'].sum()
table_day = current_date_dataframe['Date'].dt.weekday.iloc[0]
display(current_date_dataframe)
print(f"Количество:, {current_date_count}, \nДень недели:, {table_day}")

,Date,Hour,Temperature,Humidity,Wind speed,Rainfall,Snowfall,Seasons,Holiday,Functioning Day,Total_count
3096,2018-04-09,0,3.2,84,0.6,0.0,0.0,Spring,No Holiday,Yes,90
3097,2018-04-09,1,2.8,87,0.8,0.0,0.0,Spring,No Holiday,Yes,126
3098,2018-04-09,2,2.2,88,0.5,0.0,0.0,Spring,No Holiday,Yes,80
3099,2018-04-09,3,1.6,94,0.3,0.0,0.0,Spring,No Holiday,Yes,62
3100,2018-04-09,4,1.1,95,0.5,0.0,0.0,Spring,No Holiday,Yes,56
3101,2018-04-09,5,0.7,96,1.0,0.0,0.0,Spring,No Holiday,Yes,131
3102,2018-04-09,6,NaN,97,0.6,0.0,0.0,Spring,No Holiday,Yes,117
3103,2018-04-09,7,0.6,97,1.3,0.0,0.0,Spring,No Holiday,Yes,572
3104,2018-04-09,8,1.0,97,0.9,0.0,0.0,Spring,No Holiday,Yes,1426
3105,2018-04-09,9,2.6,96,1.1,0.0,0.0,Spring,No Holiday,Yes,719
3106,2018-04-09,10,5.2,73,1.0,0.0,0.0,Spring,No Holiday,Yes,276
3107,2018-04-09,11,7.5,54,0.9,0.0,0.0,Spring,No Holiday,Yes,361
3108,2018-04-09,12,NaN,44,1.7,0.0,0.0,Spring,No Holiday,Yes,1106
3109,2018-04-09,13,12.4,32,1.7,0.0,0.0,Spring,No Holiday,Yes,1291
3110,2018-04-09,14,13.9,26,2.5,0.0,0.0,Spring,No Holiday,Yes,1715
3111,2018-04-09,15,14.2,24,1.8,0.0,0.0,Spring,No Holiday,Yes,276
3112,2018-04-09,16,15.3,24,1.5,0.0,0.0,Spring,No Holiday,Yes,301
3113,2018-04-09,17,15.3,26,0.9,0.0,0.0,Spring,No Holiday,Yes,1892
3114,2018-04-09,18,14.8,24,1.3,0.0,0.0,Spring,No Holiday,Yes,1323
3115,2018-04-09,19,13.4,33,1.2,0.0,0.0,Spring,No Holiday,Yes,2215
3116,2018-04-09,20,11.7,34,0.9,0.0,0.0,Spring,No Holiday,Yes,1523
3117,2018-04-09,21,10.3,38,0.5,0.0,0.0,Spring,No Holiday,Yes,1130
3118,2018-04-09,22,9.6,41,0.5,0.0,0.0,Spring,No Holiday,Yes,599
3119,2018-04-09,23,9.6,43,1.2,0.0,0.0,Spring,No Holiday,Yes,415

Количество:, 17802,
День недели:, 0

5) Перекодируйте категориальную переменную переменную Functioning Day(рабочий или нерабочий день) в переменную типа boolean, т.е. "Yes"=True и "No" = False. Выведите количество нерабочих дней ( не часов ). День считается нерабочим, если пункт выдачи велосипедов работал менее 12 часов.

In [61]:
def get_func_day_state(state):
    if state == 'Yes':
        return True
    else:
        return False

dataframe['Functioning Day'] = dataframe['Functioning Day'].apply(get_func_day_state)
display(dataframe)

functioning_hours = dataframe.groupby(dataframe['Date'])['Functioning Day'].sum()
display(functioning_hours)
not_functioning_days_count = (functioning_hours < 12).sum()

print(f"Количество нерабочих дней: {not_functioning_days_count}")

,Date,Hour,Temperature,Humidity,Wind speed,Rainfall,Snowfall,Seasons,Holiday,Functioning Day,Total_count
0,2017-12-01,0,-5.2,37,2.2,0.0,0.0,Winter,No Holiday,True,257
1,2017-12-01,1,-5.5,38,0.8,0.0,0.0,Winter,No Holiday,True,219
2,2017-12-01,2,-6.0,39,1.0,0.0,0.0,Winter,No Holiday,True,162
3,2017-12-01,3,-6.2,40,0.9,0.0,0.0,Winter,No Holiday,True,148
4,2017-12-01,4,-6.0,36,2.3,0.0,0.0,Winter,No Holiday,True,97
...,...,...,...,...,...,...,...,...,...,...,...
8755,2018-11-30,19,4.2,34,2.6,0.0,0.0,Autumn,No Holiday,True,644
8756,2018-11-30,20,3.4,37,2.3,0.0,0.0,Autumn,No Holiday,True,359
8757,2018-11-30,21,2.6,39,0.3,0.0,0.0,Autumn,No Holiday,True,1236
8758,2018-11-30,22,2.1,41,1.0,0.0,0.0,Autumn,No Holiday,True,628
8759,2018-11-30,23,1.9,43,1.3,0.0,0.0,Autumn,No Holiday,True,843

Date
2017-12-01    24
2017-12-02    24
2017-12-03    24
2017-12-04    24
2017-12-05    24
              ..
2018-11-26    24
2018-11-27    24
2018-11-28    24
2018-11-29    24
2018-11-30    24
Name: Functioning Day, Length: 365, dtype: int64

Количество нерабочих дней: 12

6) Перекодируйте переменную Holiday (являлся ли день праздничным) в 0, если No Holiday, и 1, если Holiday. (используйте анонимную функцию lambda).

In [62]:
dataframe['Holiday'] = dataframe['Holiday'].apply(lambda x: 1 if x == 'Holiday' else 0)
display(dataframe)

,Date,Hour,Temperature,Humidity,Wind speed,Rainfall,Snowfall,Seasons,Holiday,Functioning Day,Total_count
0,2017-12-01,0,-5.2,37,2.2,0.0,0.0,Winter,0,True,257
1,2017-12-01,1,-5.5,38,0.8,0.0,0.0,Winter,0,True,219
2,2017-12-01,2,-6.0,39,1.0,0.0,0.0,Winter,0,True,162
3,2017-12-01,3,-6.2,40,0.9,0.0,0.0,Winter,0,True,148
4,2017-12-01,4,-6.0,36,2.3,0.0,0.0,Winter,0,True,97
...,...,...,...,...,...,...,...,...,...,...,...
8755,2018-11-30,19,4.2,34,2.6,0.0,0.0,Autumn,0,True,644
8756,2018-11-30,20,3.4,37,2.3,0.0,0.0,Autumn,0,True,359
8757,2018-11-30,21,2.6,39,0.3,0.0,0.0,Autumn,0,True,1236
8758,2018-11-30,22,2.1,41,1.0,0.0,0.0,Autumn,0,True,628
8759,2018-11-30,23,1.9,43,1.3,0.0,0.0,Autumn,0,True,843

7) Введите новую категориальную переменную Temperature category, которая будет равна:
- "Freezing", если температура < 0;
- "Chilly", если 0 <= температура < 15;
- "Nice", если 15 <= температура < 26;
- "Hot", если 26 <= температура.

In [63]:
def set_temperature_category(temperature):
    if temperature < 0:
        return "Freezing"
    elif (temperature >= 0) & (temperature < 15 ):
        return "Chilly"
    elif (temperature >= 15) & (temperature < 26):
        return "Nice"
    elif (temperature >= 26):
        return "Hot"

dataframe['Temperature Category'] = dataframe['Temperature'].apply(set_temperature_category)
dataframe

,Date,Hour,Temperature,Humidity,Wind speed,Rainfall,Snowfall,Seasons,Holiday,Functioning Day,Total_count,Temperature Category
0,2017-12-01,0,-5.2,37,2.2,0.0,0.0,Winter,0,True,257,Freezing
1,2017-12-01,1,-5.5,38,0.8,0.0,0.0,Winter,0,True,219,Freezing
2,2017-12-01,2,-6.0,39,1.0,0.0,0.0,Winter,0,True,162,Freezing
3,2017-12-01,3,-6.2,40,0.9,0.0,0.0,Winter,0,True,148,Freezing
4,2017-12-01,4,-6.0,36,2.3,0.0,0.0,Winter,0,True,97,Freezing
...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2018-11-30,19,4.2,34,2.6,0.0,0.0,Autumn,0,True,644,Chilly
8756,2018-11-30,20,3.4,37,2.3,0.0,0.0,Autumn,0,True,359,Chilly
8757,2018-11-30,21,2.6,39,0.3,0.0,0.0,Autumn,0,True,1236,Chilly
8758,2018-11-30,22,2.1,41,1.0,0.0,0.0,Autumn,0,True,628,Chilly
8759,2018-11-30,23,1.9,43,1.3,0.0,0.0,Autumn,0,True,843,Chilly

8) Создайте новую переменную Good weather, которая будет равна 1 (т.е. хорошая погода), если: Temperature category = "Nice", Humidity в диапазоне от 40 до 60 , скорость ветра Wind speed меньше 5.4, нет дождя (Rainfall) нет снега (Snowfall). Определите, сколько процентов наблюдений соответствует хорошей погоде.

In [64]:
dataframe['Good weather'] = dataframe.apply(lambda x: 1 if (x['Temperature Category'] == 'Nice') & (x['Humidity'] >= 40) & (x['Humidity'] <= 60) & (x['Wind speed'] < 5.4) & (x['Rainfall'] == 0.0) & (x['Snowfall'] == 0.0) else 0, axis=1)

good_weather_percent = (dataframe[dataframe['Good weather'] == 1].shape[0] / dataframe.shape[0]) * 100
display(dataframe)
print(f"Хорошая погода - {round(good_weather_percent, 2)} %")

,Date,Hour,Temperature,Humidity,Wind speed,Rainfall,Snowfall,Seasons,Holiday,Functioning Day,Total_count,Temperature Category,Good weather
0,2017-12-01,0,-5.2,37,2.2,0.0,0.0,Winter,0,True,257,Freezing,0
1,2017-12-01,1,-5.5,38,0.8,0.0,0.0,Winter,0,True,219,Freezing,0
2,2017-12-01,2,-6.0,39,1.0,0.0,0.0,Winter,0,True,162,Freezing,0
3,2017-12-01,3,-6.2,40,0.9,0.0,0.0,Winter,0,True,148,Freezing,0
4,2017-12-01,4,-6.0,36,2.3,0.0,0.0,Winter,0,True,97,Freezing,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2018-11-30,19,4.2,34,2.6,0.0,0.0,Autumn,0,True,644,Chilly,0
8756,2018-11-30,20,3.4,37,2.3,0.0,0.0,Autumn,0,True,359,Chilly,0
8757,2018-11-30,21,2.6,39,0.3,0.0,0.0,Autumn,0,True,1236,Chilly,0
8758,2018-11-30,22,2.1,41,1.0,0.0,0.0,Autumn,0,True,628,Chilly,0
8759,2018-11-30,23,1.9,43,1.3,0.0,0.0,Autumn,0,True,843,Chilly,0

Хорошая погода - 9.27 %

9) Сгруппируйте данные по сезонам (Seasons), внутри сезона по категории погоды (Temperature category) и вывести для полученной группировки количество арендованных велосипедов. Вывести результаты в виде сгруппированной таблицы (через groupby) и в виде сводной таблицы (pivot_table).

In [65]:
grouped = dataframe.groupby(['Seasons', 'Temperature Category'])['Total_count'].sum()

pivot = dataframe.pivot_table(
    index='Seasons',
    columns='Temperature Category',
    values='Total_count',
    aggfunc='sum'
)

display(grouped)
display(pivot)

Seasons  Temperature Category
Autumn   Chilly                   775694
         Freezing                  12035
         Hot                      134156
         Nice                     811498
Spring   Chilly                   587211
         Freezing                   6331
         Hot                       52993
         Nice                     928572
Summer   Hot                     1315525
         Nice                     892664
Winter   Chilly                   215221
         Freezing                 258570
Name: Total_count, dtype: int64

Temperature Category    Chilly  Freezing        Hot      Nice
Seasons
Autumn                775694.0   12035.0   134156.0  811498.0
Spring                587211.0    6331.0    52993.0  928572.0
Summer                     NaN       NaN  1315525.0  892664.0
Winter                215221.0  258570.0        NaN       NaN

10) Определите сезон и температуру, при которых выдается наибольшее и наименьшееколичество велосипедов.

In [66]:
bikes_max_count = grouped.max()
bikes_min_count = grouped.min()

max_season, max_temp = grouped.idxmax()
min_season, min_temp = grouped.idxmin()

print(f"Наибольшее количество выданных велосипедов - сезон: {max_season}, погода: {max_temp} - {bikes_max_count}")
print(f"Наименьшее количество выданных велосипедов - сезон: {min_season}, погода: {min_temp} - {bikes_min_count}")

Наибольшее количество выданных велосипедов - сезон: Summer, погода: Hot - 1315525
Наименьшее количество выданных велосипедов - сезон: Spring, погода: Freezing - 6331