# Лабораторная работа №2

In [36]:
import pandas as pd
from datetime import datetime

In [37]:
dataframe = pd.read_csv("../lab2/data/BikeData.csv")
dataframe

,Date,Hour,Temperature,Humidity,Wind speed,Rainfall,Snowfall,Seasons,Holiday,Functioning Day,Partner 1,Partner 2
0,01/12/2017,0,-5.2,37,2.2,0.0,0.0,Winter,No Holiday,Yes,207,50
1,01/12/2017,1,-5.5,38,0.8,0.0,0.0,Winter,No Holiday,Yes,139,80
2,01/12/2017,2,-6.0,39,1.0,0.0,0.0,Winter,No Holiday,Yes,22,140
3,01/12/2017,3,-6.2,40,0.9,0.0,0.0,Winter,No Holiday,Yes,43,105
4,01/12/2017,4,-6.0,36,2.3,0.0,0.0,Winter,No Holiday,Yes,59,38
...,...,...,...,...,...,...,...,...,...,...,...,...
8755,30/11/2018,19,4.2,34,2.6,0.0,0.0,Autumn,No Holiday,Yes,467,177
8756,30/11/2018,20,3.4,37,2.3,0.0,0.0,Autumn,No Holiday,Yes,296,63
8757,30/11/2018,21,2.6,39,0.3,0.0,0.0,Autumn,No Holiday,Yes,571,665
8758,30/11/2018,22,2.1,41,1.0,0.0,0.0,Autumn,No Holiday,Yes,171,457
8759,30/11/2018,23,1.9,43,1.3,0.0,0.0,Autumn,No Holiday,Yes,442,401

1) Создайте новую переменную Total_count, в которую записать общее количество арендованных велосипедов за каждый час.

In [38]:
dataframe['Total_count'] = dataframe['Partner 1'] + dataframe['Partner 2']
dataframe

,Date,Hour,Temperature,Humidity,Wind speed,Rainfall,Snowfall,Seasons,Holiday,Functioning Day,Partner 1,Partner 2,Total_count
0,01/12/2017,0,-5.2,37,2.2,0.0,0.0,Winter,No Holiday,Yes,207,50,257
1,01/12/2017,1,-5.5,38,0.8,0.0,0.0,Winter,No Holiday,Yes,139,80,219
2,01/12/2017,2,-6.0,39,1.0,0.0,0.0,Winter,No Holiday,Yes,22,140,162
3,01/12/2017,3,-6.2,40,0.9,0.0,0.0,Winter,No Holiday,Yes,43,105,148
4,01/12/2017,4,-6.0,36,2.3,0.0,0.0,Winter,No Holiday,Yes,59,38,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,30/11/2018,19,4.2,34,2.6,0.0,0.0,Autumn,No Holiday,Yes,467,177,644
8756,30/11/2018,20,3.4,37,2.3,0.0,0.0,Autumn,No Holiday,Yes,296,63,359
8757,30/11/2018,21,2.6,39,0.3,0.0,0.0,Autumn,No Holiday,Yes,571,665,1236
8758,30/11/2018,22,2.1,41,1.0,0.0,0.0,Autumn,No Holiday,Yes,171,457,628
8759,30/11/2018,23,1.9,43,1.3,0.0,0.0,Autumn,No Holiday,Yes,442,401,843

2) Удалите ряды Partner 1 и Partner 2

In [39]:
dataframe = dataframe.drop(columns=['Partner 1', 'Partner 2'])
dataframe

,Date,Hour,Temperature,Humidity,Wind speed,Rainfall,Snowfall,Seasons,Holiday,Functioning Day,Total_count
0,01/12/2017,0,-5.2,37,2.2,0.0,0.0,Winter,No Holiday,Yes,257
1,01/12/2017,1,-5.5,38,0.8,0.0,0.0,Winter,No Holiday,Yes,219
2,01/12/2017,2,-6.0,39,1.0,0.0,0.0,Winter,No Holiday,Yes,162
3,01/12/2017,3,-6.2,40,0.9,0.0,0.0,Winter,No Holiday,Yes,148
4,01/12/2017,4,-6.0,36,2.3,0.0,0.0,Winter,No Holiday,Yes,97
...,...,...,...,...,...,...,...,...,...,...,...
8755,30/11/2018,19,4.2,34,2.6,0.0,0.0,Autumn,No Holiday,Yes,644
8756,30/11/2018,20,3.4,37,2.3,0.0,0.0,Autumn,No Holiday,Yes,359
8757,30/11/2018,21,2.6,39,0.3,0.0,0.0,Autumn,No Holiday,Yes,1236
8758,30/11/2018,22,2.1,41,1.0,0.0,0.0,Autumn,No Holiday,Yes,628
8759,30/11/2018,23,1.9,43,1.3,0.0,0.0,Autumn,No Holiday,Yes,843

3) Преобразуйте переменную Date к стандартной форме (to_datetime).

In [40]:
# dataframe['Date'] = dataframe['Date'].dt.strftime('%d.%m.%Y')
dataframe['Date'] = pd.to_datetime(dataframe['Date'], format='%d/%m/%Y')
dataframe

,Date,Hour,Temperature,Humidity,Wind speed,Rainfall,Snowfall,Seasons,Holiday,Functioning Day,Total_count
0,2017-12-01,0,-5.2,37,2.2,0.0,0.0,Winter,No Holiday,Yes,257
1,2017-12-01,1,-5.5,38,0.8,0.0,0.0,Winter,No Holiday,Yes,219
2,2017-12-01,2,-6.0,39,1.0,0.0,0.0,Winter,No Holiday,Yes,162
3,2017-12-01,3,-6.2,40,0.9,0.0,0.0,Winter,No Holiday,Yes,148
4,2017-12-01,4,-6.0,36,2.3,0.0,0.0,Winter,No Holiday,Yes,97
...,...,...,...,...,...,...,...,...,...,...,...
8755,2018-11-30,19,4.2,34,2.6,0.0,0.0,Autumn,No Holiday,Yes,644
8756,2018-11-30,20,3.4,37,2.3,0.0,0.0,Autumn,No Holiday,Yes,359
8757,2018-11-30,21,2.6,39,0.3,0.0,0.0,Autumn,No Holiday,Yes,1236
8758,2018-11-30,22,2.1,41,1.0,0.0,0.0,Autumn,No Holiday,Yes,628
8759,2018-11-30,23,1.9,43,1.3,0.0,0.0,Autumn,No Holiday,Yes,843

4) Определите сколько велосипедов было выдано в день, месяц и число которого совпадает с днем выполнения этого задания. Определите, какой это был день недели.

In [43]:
# current_date = datetime.now().date()
# current_month = current_date.month
# current_day = current_date.day

# current_date_dataframe = dataframe[(dataframe['Date'].dt.month == current_month) & (dataframe['Date'].dt.day == current_day)]
# current_date_count = current_date_dataframe['Total_count'].sum()
# table_day = current_date_dataframe['Date'].dt.weekday.iloc[0]
# display(current_date_dat'''aframe)
# print(f"количество:\t{current_date_count}\nдень недели:\t{table_day}")



current_date = datetime.now().date()
current_month = current_date.month
current_day = current_date.day

current_date_dataframe = dataframe[(dataframe['Date'].dt.month == current month) & (dataframe['Date'].dt.day == current_day)]
current_date_count = current_date_dataframe['Total_count'].sum()
table_day = current_date_dataframe['Date'].dt.weekday.iloc[0]
display(current_date_dataframe)
print(f"количество:\t{current_date_count}\nдень недели:\t{table_day}")

SyntaxError: invalid syntax. Perhaps you forgot a comma? (3379772311.py, line 17)